meno = input("Ako sa voláš? ")
print("Ahoj", meno)
input("Koľko máš rokov? ")
input("Akú máš výšku? ")
input("Aké je tvoje číslo topánok? ")
input("Aká je tvoja obľúbená farba? ")
x = input("Vieš na čo sú mi tieto informácie? ")
ano = (x=="ano") or (x=="viem")
if ano:
    print("Neklam! Nevieš!)")
nie = (x=="nie") or (x=="neviem")
if nie:
    print("Nevadí :)")
print()
print()
print("FFFFF U   U  CCCC K  K   Y   Y  OOOO  U    U  !!!!!")
print("F     U   U C     K K    Y   Y O    O U    U  !!!!!")
print("FFF   U   U C     KK      Y Y  O    O U    U   !!!")
print("F     U   U C     K K      Y   O    O U    U    !")
print("F      UUU   CCCC K  K     Y    OOOO   UUUU     O")
print()
print()
print()
input("Ďakujem za vyplnenie dotazníka. Pre ukončenie stlačte ENTER.")
